export const FORM_ACTIONS = {
  CHANGE_INPUT: 'CHANGE_INPUT',
  GET_STATE: 'GET_STATE',
  CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
}
